#
# @Author: wjm
# @Date: 2019-10-13 21:45:10
# @LastEditTime: 2019-10-13 21:46:06
# @Description: file content
# 

name: Net
algorithm: moe #maunetv4_ns #ugcn_s4nba0  pan_unfolding_v4
nEpochs: 1000
gpu_mode: True
save_best: True
gpus: [0]
threads:  8 #num_works
log_dir: logs/


seed: 123 #123
checkpoint: weights
data_dir_train: /home/Shawalt/Demos/ImageFusion/DataSet/NBU_DataSet/Satellite_Dataset/DataSet_TIF/6_WorldView-3
data_dir_eval: /home/Shawalt/Demos/ImageFusion/DataSet/NBU_DataSet/Satellite_Dataset/DataSet_TIF/6_WorldView-3

source_ms: MS_256
source_pan: PAN_1024

pretrain:
  pretrained: False
  pre_sr: latest.pth
  pre_folder: /home/Shawalt/Demos/ImageFusion/FAME-Net_back/FAME-Net/weights/moe_4_1730195788

test:  #用于指标测试的代码
  algorithm: moe #pannetffft
  type: test #[test, eval]
  data_dir: wv3_data_dev/valid
  source_ms: MS_256
  source_pan: PAN_1024 #moe_bal_4_1681220224
  model: ~
  #model: ugcn_s4nb_4_1630368984/best.pth
  save_dir: result/moe_wv3/

data:
  upsacle:  4
  batch_size: 4 #4
  patch_size: 32
  data_augmentation: False
  n_colors: 4
  rgb_range: 255
  normalize : False
  
schedule:
  lr: 5e-4 #5e-6 #1e-2
  decay: 500
  gamma: 0.1
  optimizer: ADAM #[ADAM, SGD, RMSprop]
  momentum: 0.9 #SGD momentum
  beta1: 0.9 #ADAM beta1
  beta2: 0.999 #ADAM beta
  epsilon: 1e-8 #ADAM epsilon
  alpha: 0.9 #RMSprop alpha
  weight_dency: 0
  gclip: 4 #0.4   #0.4  0.04
  loss: L1
  use_YCbCr: False


